#! /bin/bash

JAR='jar'

rm -rf jartmp
mkdir -p jartmp
cd jartmp

# Unjar jar files generated by the buckminster build.
find ../out -name '*.jar' ! -name *junit* -print0 | while read -d $'\0' file
do
	echo "Unjarring $file"
	cat $file | $JAR x
done

# Unjar jar files contained in previous jar files and remove them.
find . -name '*.jar' -print0 | while read -d $'\0' file
do
	echo "Unjarring $file"
	cat $file | $JAR x
	rm $file
done

# Remove unneccesary directories.
rm -rf 'META-INF'
rm -rf 'lib'

# Create a single jar with all class files.
echo 'Jarring spoofax-libs.jar'
$JAR cf ../spoofax-libs.jar .
cd ..
rm -rf jartmp
